Screens:
  Main:
    Properties:
      Fill: =RGBA(243, 242, 241, 1)
      LoadingSpinnerColor: =RGBA(56, 96, 178, 1)
    Children:
      - Rectangle1:
          Control: Rectangle@2.3.0
          Properties:
            BorderColor: =RGBA(31, 41, 55, 1)
            Fill: =RGBA(31, 41, 55, 1)
            Height: =80
            Width: =1366
      - Container1:
          Control: GroupContainer@1.4.0
          Variant: ManualLayout
          Properties:
            Fill: =RGBA(255, 255, 255, 1)
            Height: =55
            RadiusBottomLeft: =10
            RadiusBottomRight: =10
            RadiusTopLeft: =10
            RadiusTopRight: =10
            Width: =Self.Height
            X: =40
            Y: =Rectangle1.Height / 2 - Self.Height / 2
          Children:
            - Label1:
                Control: Label@2.5.1
                Properties:
                  Align: =Align.Center
                  BorderColor: =RGBA(0, 18, 107, 1)
                  Font: =Font.'Open Sans'
                  FontWeight: =FontWeight.Bold
                  Height: =Parent.Height
                  Size: =16
                  Text: ="DI"
                  Width: =Parent.Width
      - Label2:
          Control: Label@2.5.1
          Properties:
            BorderColor: =RGBA(0, 18, 107, 1)
            Color: =RGBA(255, 255, 255, 1)
            Font: =Font.'Open Sans'
            FontWeight: =FontWeight.Semibold
            Height: =Container1.Height
            Size: =18
            Text: ="Gestión de Residuos"
            Width: =282
            X: =120
            Y: =12
      - Label4:
          Control: Label@2.5.1
          Properties:
            BorderColor: =RGBA(0, 18, 107, 1)
            Color: =RGBA(31, 41, 55, 1)
            Font: =Font.'Open Sans'
            FontWeight: =FontWeight.Bold
            Size: =20
            Text: ="Hola, " & First(Split(User().FullName, " ")).Value
            Width: =550
            X: =53
            Y: =162
      - Label5:
          Control: Label@2.5.1
          Properties:
            BorderColor: =RGBA(0, 18, 107, 1)
            Color: =RGBA(77, 77, 77, 1)
            Font: =Font.'Open Sans'
            Height: =36
            Size: =15
            Text: ="Selecciona una acción para comenzar."
            Width: =400
            X: =53
            Y: =205
      - Icon3:
          Control: Classic/Icon@2.5.0
          Properties:
            BorderColor: =RGBA(0, 18, 107, 1)
            Color: =RGBA(219, 219, 219, 1)
            Height: =35
            Icon: =Icon.Person
            Width: =35
            X: =1274
            Y: =22
      - Label6:
          Control: Label@2.5.1
          Properties:
            Align: =Align.Right
            BorderColor: =RGBA(0, 18, 107, 1)
            Color: =RGBA(255, 255, 255, 1)
            Font: =Font.'Open Sans'
            Height: =41
            Text: =User().FullName
            Width: =308
            X: =960
            Y: =19
      - ContainerBotones:
          Control: GroupContainer@1.4.0
          Variant: AutoLayout
          Properties:
            DropShadow: =DropShadow.None
            Height: =347
            LayoutAlignItems: =LayoutAlignItems.Center
            LayoutDirection: =LayoutDirection.Horizontal
            LayoutGap: =40
            PaddingBottom: =8
            PaddingLeft: =8
            PaddingRight: =8
            PaddingTop: =8
            Width: =1260
            X: =(Parent.Width - Self.Width) / 2
            Y: =310
          Children:
            - ContenedorCrearDI:
                Control: GroupContainer@1.4.0
                Variant: ManualLayout
                Properties:
                  Fill: =RGBA(255, 255, 255, 1)
                  LayoutMinHeight: =16
                  LayoutMinWidth: =16
                Children:
                  - Label3:
                      Control: Label@2.5.1
                      Properties:
                        BorderColor: =RGBA(0, 18, 107, 1)
                        Font: =Font.'Open Sans'
                        FontWeight: =FontWeight.Bold
                        Size: =16
                        Text: ="Introducir KGs Mes"
                        Width: =220
                        X: =28
                        Y: =161
                  - Circle1:
                      Control: Circle@2.3.0
                      Properties:
                        BorderColor: =RGBA(0, 18, 107, 1)
                        Fill: =RGBA(239, 246, 255, 1)
                        Height: =300
                        Width: =Self.Height
                        X: =268
                  - Circle2:
                      Control: Circle@2.3.0
                      Properties:
                        BorderColor: =RGBA(0, 18, 107, 1)
                        Fill: =RGBA(240, 245, 250, 1)
                        Height: =72
                        Width: =72
                        X: =28
                        Y: =28
                  - Icon1:
                      Control: Classic/Icon@2.5.0
                      Properties:
                        BorderColor: =RGBA(0, 18, 107, 1)
                        Color: =RGBA(37, 99, 235, 1)
                        Height: =48
                        Icon: =Icon.Cancel
                        Rotation: =45
                        Width: =45
                        X: =40
                        Y: =40
                  - Label3_1:
                      Control: Label@2.5.1
                      Properties:
                        BorderColor: =RGBA(0, 18, 107, 1)
                        Color: =RGBA(100, 116, 139, 1)
                        Font: =Font.'Open Sans'
                        Height: =64
                        Text: ="Generar un nuevo documento mensual y envía los DIs a firma por receptor."
                        Width: =269
                        X: =28
                        Y: =213
                  - ButtonCrearDI:
                      Control: Classic/Button@2.2.0
                      Properties:
                        BorderColor: =ColorFade(Self.Fill, -15%)
                        Color: =RGBA(255, 255, 255, 1)
                        DisabledBorderColor: =RGBA(166, 166, 166, 1)
                        Fill: =RGBA(0, 0, 0, 0)
                        Font: =Font.'Open Sans'
                        Height: =Parent.Height
                        HoverBorderColor: =RGBA(0, 120, 212, 1)
                        HoverFill: =RGBA(37, 99, 235, 0.05)
                        OnSelect: =Navigate(FormularioMensual, Transition.Push)
                        PressedBorderColor: =Self.Fill
                        PressedColor: =Self.Fill
                        PressedFill: =RGBA(37, 99, 235, 0.1)
                        RadiusBottomLeft: =4
                        RadiusBottomRight: =4
                        RadiusTopLeft: =4
                        RadiusTopRight: =4
                        Text: =
                        Width: =Parent.Width
            - ContenedorHistoricos:
                Control: GroupContainer@1.4.0
                Variant: ManualLayout
                Properties:
                  Fill: =RGBA(255, 255, 255, 1)
                  LayoutMinHeight: =16
                  LayoutMinWidth: =16
                Children:
                  - Label3_4:
                      Control: Label@2.5.1
                      Properties:
                        BorderColor: =RGBA(0, 18, 107, 1)
                        Font: =Font.'Open Sans'
                        FontWeight: =FontWeight.Bold
                        Size: =16
                        Text: ="Histórico Acuerdos"
                        Width: =240
                        X: =28
                        Y: =161
                  - Circle1_2:
                      Control: Circle@2.3.0
                      Properties:
                        BorderColor: =RGBA(0, 18, 107, 1)
                        Fill: =RGBA(240, 253, 244, 1)
                        Height: =300
                        Width: =Self.Height
                        X: =268
                  - Circle2_2:
                      Control: Circle@2.3.0
                      Properties:
                        BorderColor: =RGBA(0, 18, 107, 1)
                        Fill: =RGBA(240, 250, 243, 1)
                        Height: =72
                        Width: =72
                        X: =28
                        Y: =28
                  - Label3_5:
                      Control: Label@2.5.1
                      Properties:
                        BorderColor: =RGBA(0, 18, 107, 1)
                        Color: =RGBA(100, 116, 139, 1)
                        Font: =Font.'Open Sans'
                        Height: =64
                        Text: ="Consultar estado de firma y descargar históricos."
                        Width: =296
                        X: =28
                        Y: =213
                  - imgSVGPATools_1:
                      Control: Image@2.2.3
                      Properties:
                        Height: =38
                        Image: = "data:image/svg+xml; utf-8, " & EncodeUrl($"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='#15803d' stroke-width='2'>   <line x1='22' y1='2' x2='11' y2='13'></line>   <polygon points='22 2 15 22 11 13 2 9 22 2'></polygon> </svg>")
                        Width: =49
                        X: =38
                        Y: |
                          =47
                  - ButtonHistorico:
                      Control: Classic/Button@2.2.0
                      Properties:
                        BorderColor: =ColorFade(Self.Fill, -15%)
                        Color: =RGBA(255, 255, 255, 1)
                        DisabledBorderColor: =RGBA(166, 166, 166, 1)
                        Fill: =RGBA(0, 0, 0, 0)
                        Font: =Font.'Open Sans'
                        Height: =Parent.Height
                        HoverBorderColor: =RGBA(56, 235, 38, 1)
                        HoverColor: =RGBA(255, 255, 255, 0)
                        HoverFill: =RGBA(56, 235, 38, 0.05)
                        OnSelect: =Navigate(Historial)
                        PressedBorderColor: =Self.Fill
                        PressedColor: =Self.Fill
                        PressedFill: =RGBA(56, 235, 38, 0.1)
                        RadiusBottomLeft: =4
                        RadiusBottomRight: =4
                        RadiusTopLeft: =4
                        RadiusTopRight: =4
                        Text: =
                        Width: =Parent.Width
